### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by frederico-miranda** [ricardovaltierra/sample_app#4]
On branch 'advanced-login', source file 'app/helpers/sessions_helper.rb' :
```
def forget(user):
  user.forget
  ...
```
It calls a method 'forget' of an 'user' object (which is presumably an instance of the User model defined at 'app/models/user.rb'), but there is no such method defined at the 'User' class.

**Comment by ricardovaltierra** [comment]
The method required to implement on the User model was added and test `login with valid information followed by logout` is now passing
